Petites corrections
Gillespie59/article-zone pull request #2
Opened 2016-11-09 13:26 UTC by RemiEven

2016-11-09 16:23 UTC, Kize requested changes

2016-11-09 16:23 UTC, Kize commented on README.md
>  Maintenant qu'Angular2 est officiellement disponible, il est tant pour nous tous de comprendre les méandres de cette
il est tant => il est temps

2016-11-09 16:23 UTC, Kize commented on README.md
>  pour débuter un nouveau projet Angular2, vous avez sûrement du importer une librairie *zone.js*, afin de faire fonctionner
vous avez sûrement du => dû

2016-11-09 16:23 UTC, Kize commented on README.md
>  Si nous nous mettons à la place d'une VM JavaScript, nous avons en fait, au minimum, deux stack d'exécutions. La principale correspond
deux stack d'exécutions => deux **_stacks d'exécution_**

2016-11-09 16:23 UTC, Kize commented on README.md
>  * Intéragir avec le cycle de vie des tâches asynchrones, à l'aide de *hooks*
Intéragir => Interagir

2016-11-09 16:23 UTC, Kize commented on README.md
> +Comment est-il possible d'intéragir avec le cycle de vie de ces tâches? Tout simplement, parce que la librairie
d'intéragir => d'interagir

2016-11-09 16:23 UTC, Kize commented on README.md
>  faire exécuter des traitements synchrones et asynchrones. Ces contextes d'exécution vons nous permettre de
Ces contextes d'exécution vons => Ces contextes d'exécution vont

2016-11-11 15:03 UTC, Gillespie59 commented
J'ai mergé à la main. Merci

2016-11-11 15:03 UTC, closed without merging